### ISSUE TITLE
Got an error from accessory_binary_genes.py

### ISSUE THREAD

**Issue by chantisakee** [johnjare/panaroo_scripts#1]
Hi,

I am trying to run accessory_binary_genes.py and got an error of as shown here.

Traceback (most recent call last):
  File "/panaroo_scripts/accessory_binary_genes/accessory_binary_genes.py", line 35, in <module>
    df["sum"] = df.sum(axis=1)
                ^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/frame.py", line 11312, in sum
    result = super().sum(axis, skipna, numeric_only, min_count, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/generic.py", line 12070, in sum
    return self._min_count_stat_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/generic.py", line 12053, in _min_count_stat_function
    return self._reduce(
           ^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/frame.py", line 11204, in _reduce
    res = df._mgr.reduce(blk_func)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1459, in reduce
    nbs = blk.reduce(func)
          ^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 377, in reduce
    result = func(self.values)
             ^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/frame.py", line 11136, in blk_func
    return op(values, axis=axis, skipna=skipna, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//panaroo_script/lib/python3.12/site-packages/pandas/core/nanops.py", line 85, in _f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/nanops.py", line 404, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/nanops.py", line 477, in newfunc
    return func(values, axis=axis, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/pandas/core/nanops.py", line 646, in nansum
    the_sum = values.sum(axis, dtype=dtype_sum)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/panaroo_script/lib/python3.12/site-packages/numpy/core/_methods.py", line 49, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only concatenate str (not "int") to str

Thank you

**Comment by johnjare** [comment]
Hi @chantisakee. My best guess is this issue is due to your version of Pandas being too new. You could give Pandas v1.2.0 a shot a see if that fixes the problem. This script was from my PhD work and is not being maintained (I now use a different GitHub account all together https://github.com/DOH-JDJ0303). That said, this is something I have been wanting to circle back to, so I may have an updated version in the near future. May I ask what you are running this on?
